# The workflow to build binary with Actions

name: Build qbittorrent-nox armhf

# Controls when the action will run. 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: docker env
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: run build
        uses: docker://arm32v7/alpine
        with:
          args: /bin/ash -c "apk update && apk add bash && bash ./qbittorrent-static.sh all -i --lt \"${{ secrets.LT_VERSION }}\" --qt \"${{ secrets.QBIT_VERSION }}\" ${{ secrets.EXTRA_ARGS }} -v && cp qb-build/completed/qbittorrent-nox ./qbittorrent-nox.armhf"

      - name: archive binary
        uses: actions/upload-artifact@v2
        with:
          name: qbittorrent-nox_lt_${{ secrets.LT_VERSION }}_qb_${{ secrets.QBIT_VERSION }}
          path: qbittorrent-nox.armhf

      - name: archive logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: qb-build/logs 

      - name: result
        run: echo "This job's status is ${{ job.status }}."
